# Generated by Django 4.2.3 on 2023-07-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='documents')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=10, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_msg',
            field=models.TextField(max_length=100, verbose_name='내용'),
        ),
    ]
