# Generated by Django 4.2.3 on 2023-07-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_uploadphoto_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='fileName',
            field=models.CharField(max_length=10, verbose_name='파일이름'),
        ),
        migrations.AlterField(
            model_name='uploadphoto',
            name='files',
            field=models.TextField(),
        ),
    ]
