# Generated by Django 4.2.3 on 2023-07-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_uploadphoto_filename_alter_uploadphoto_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='fileName',
            field=models.CharField(max_length=30, verbose_name='파일이름'),
        ),
    ]
