# Generated by Django 4.2.3 on 2023-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_uploadphoto_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
