# Generated by Django 4.2.3 on 2023-07-28 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_uploadphoto_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadphoto',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadphoto',
            name='fileName',
            field=models.CharField(default='name', max_length=30, verbose_name='파일이름'),
        ),
        migrations.AlterField(
            model_name='uploadphoto',
            name='files',
            field=models.TextField(default='fiel', max_length=100, verbose_name='내용'),
        ),
    ]
