# Generated by Django 4.2.3 on 2023-07-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_uploadphoto_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='files',
            field=models.FileField(default='fiel', upload_to='', verbose_name='이미지 base64'),
        ),
    ]
