# Generated by Django 4.2.3 on 2023-07-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_uploadphoto_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoto',
            name='files',
            field=models.FileField(default='files', upload_to='images', verbose_name='이미지 base64'),
        ),
    ]
